server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.100.42.118:3306/seata?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: "Root123456"
swagger:
  enable: true  #项目是否开启swagger
  basic:
    enable: false #是否开启权限验证
    username: tracy #账号
    password: 123456 #密码